-- MySQL Script generated by MySQL Workbench
-- Mon May  7 00:43:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_db` DEFAULT CHARACTER SET utf8 ;
USE `todo_db` ;

-- -----------------------------------------------------
-- Table `todo_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`user` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_fname` VARCHAR(45) NULL,
  `user_lname` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`todo_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`todo_items` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`todo_items` (
  `todo_items_id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `is_done` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`todo_items_id`, `user_user_id`),
  UNIQUE INDEX `todo_items_id_UNIQUE` (`todo_items_id` ASC),
  INDEX `fk_todo_items_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_todo_items_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `todo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`tags` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`tags` (
  `tags_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NULL DEFAULT ' ',
  PRIMARY KEY (`tags_id`),
  UNIQUE INDEX `tags_id_UNIQUE` (`tags_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`todo_items_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`todo_items_tags` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`todo_items_tags` (
  `todo_items_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  `tags_tags_id` INT NOT NULL,
  `todo_items_todo_items_id` INT NOT NULL,
  `todo_items_user_user_id` INT NOT NULL,
  PRIMARY KEY (`todo_items_id`, `tags_id`, `tags_tags_id`, `todo_items_todo_items_id`, `todo_items_user_user_id`),
  INDEX `fk_todo_items_tags_tags1_idx` (`tags_tags_id` ASC),
  INDEX `fk_todo_items_tags_todo_items1_idx` (`todo_items_todo_items_id` ASC, `todo_items_user_user_id` ASC),
  CONSTRAINT `fk_todo_items_tags_tags1`
    FOREIGN KEY (`tags_tags_id`)
    REFERENCES `todo_db`.`tags` (`tags_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_items_tags_todo_items1`
    FOREIGN KEY (`todo_items_todo_items_id` , `todo_items_user_user_id`)
    REFERENCES `todo_db`.`todo_items` (`todo_items_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

    
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
