-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 20:47:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `User_name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `User_name_UNIQUE` (`User_name` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Todo` (
  `idList` INT NOT NULL,
  `Created_at` DATE NULL,
  `Updated_at` DATE NULL,
  `Title` VARCHAR(45) NULL,
  `Descreption` VARCHAR(500) NULL,
  `DeadLine` DATE NULL,
  `Done` TINYINT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idList`),
  INDEX `fk_List_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_List_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `idComment` INT NOT NULL,
  `Body` VARCHAR(500) NULL,
  `Created_at` DATE NULL,
  `Updated_at` DATE NULL,
  `User_idUser` INT NOT NULL,
  `Todo_idList` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Comment_Todo1_idx` (`Todo_idList` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Todo1`
    FOREIGN KEY (`Todo_idList`)
    REFERENCES `mydb`.`Todo` (`idList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `idCategory` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Created_at` DATE NULL,
  `Updated_at` DATE NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Todo_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Todo_Category` (
  `idTodo_Category` INT NOT NULL,
  `Category_idCategory` INT NOT NULL,
  `Todo_idList` INT NOT NULL,
  PRIMARY KEY (`idTodo_Category`),
  INDEX `fk_Todo_Category_Category1_idx` (`Category_idCategory` ASC),
  INDEX `fk_Todo_Category_Todo1_idx` (`Todo_idList` ASC),
  CONSTRAINT `fk_Todo_Category_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Todo_Category_Todo1`
    FOREIGN KEY (`Todo_idList`)
    REFERENCES `mydb`.`Todo` (`idList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
