-- MySQL Script generated by MySQL Workbench
-- Sat Mar 24 17:30:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jamshidDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jamshidDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jamshidDB` DEFAULT CHARACTER SET utf8 ;
USE `jamshidDB` ;

-- -----------------------------------------------------
-- Table `jamshidDB`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamshidDB`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jamshidDB`.`ToDo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamshidDB`.`ToDo` (
  `idtodo` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `createddate` DATE NOT NULL,
  `due` DATE NOT NULL,
  `updatedAt` DATE NULL,
  `status` TINYINT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idtodo`, `category_idcategory`),
  INDEX `fk_ToDo_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_ToDo_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `jamshidDB`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jamshidDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamshidDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ToDo_idtodo` INT NOT NULL,
  PRIMARY KEY (`idUser`, `ToDo_idtodo`),
  INDEX `fk_User_ToDo_idx` (`ToDo_idtodo` ASC),
  CONSTRAINT `fk_User_ToDo`
    FOREIGN KEY (`ToDo_idtodo`)
    REFERENCES `jamshidDB`.`ToDo` (`idtodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
