-- MySQL Script generated by MySQL Workbench
-- 07/18/18 13:08:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema listTodo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema listTodo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listTodo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `listTodo` ;

-- -----------------------------------------------------
-- Table `listTodo`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listTodo`.`Users` (
  `id_Users` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(25) NOT NULL,
  `Last_Name` VARCHAR(25) NOT NULL,
  `User_Name` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listTodo`.`Todo_List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listTodo`.`Todo_List` (
  `id_Todo` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(75) NOT NULL,
  `Done Status` VARCHAR(10) NULL,
  `Date` INT NOT NULL,
  `Users_id_Users` INT NOT NULL,
  PRIMARY KEY (`id_Todo`),
  INDEX `fk_Todo_List_Users_idx` (`Users_id_Users` ASC),
  CONSTRAINT `fk_Todo_List_Users`
    FOREIGN KEY (`Users_id_Users`)
    REFERENCES `listTodo`.`Users` (`id_Users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listTodo`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listTodo`.`Tags` (
  `id_Tags` INT NOT NULL AUTO_INCREMENT,
  `Tag_ Description` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_Tags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listTodo`.`Todo_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listTodo`.`Todo_Tag` (
  `Todo_List_id_Todo` INT NOT NULL,
  `Tags_id_Tags` INT NOT NULL,
  INDEX `fk_Todo_Tag_Todo_List1_idx` (`Todo_List_id_Todo` ASC),
  INDEX `fk_Todo_Tag_Tags1_idx` (`Tags_id_Tags` ASC),
  CONSTRAINT `fk_Todo_Tag_Todo_List1`
    FOREIGN KEY (`Todo_List_id_Todo`)
    REFERENCES `listTodo`.`Todo_List` (`id_Todo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Todo_Tag_Tags1`
    FOREIGN KEY (`Tags_id_Tags`)
    REFERENCES `listTodo`.`Tags` (`id_Tags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
