-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 19:19:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_single_user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_single_user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_single_user` DEFAULT CHARACTER SET utf8 ;
USE `todo_single_user` ;

-- -----------------------------------------------------
-- Table `todo_single_user`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_single_user`.`lists` (
  `list_id` INT NOT NULL,
  `list_name` VARCHAR(45) NOT NULL,
  `list_description` VARCHAR(255) NULL,
  PRIMARY KEY (`list_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_single_user`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_single_user`.`tags` (
  `tag_id` INT NOT NULL,
  `tag_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_single_user`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_single_user`.`tasks` (
  `taks_id` INT NOT NULL,
  `list_id_reference` INT NOT NULL,
  `task_tag_id-reference` INT NULL DEFAULT NULL,
  `task_description` VARCHAR(45) NOT NULL,
  `task_completed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`taks_id`),
  INDEX `task_to_list_idx` (`list_id_reference` ASC) VISIBLE,
  INDEX `task_to_tag_idx` (`task_tag_id-reference` ASC) VISIBLE,
  CONSTRAINT `task_to_list`
    FOREIGN KEY (`list_id_reference`)
    REFERENCES `todo_single_user`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_to_tag`
    FOREIGN KEY (`task_tag_id-reference`)
    REFERENCES `todo_single_user`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_single_user`.`reminders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_single_user`.`reminders` (
  `reminder_id` INT NOT NULL,
  `task_id_reference` INT NOT NULL,
  `reminder_description` VARCHAR(120) NOT NULL,
  `reminder_date_point` DATETIME NOT NULL,
  PRIMARY KEY (`reminder_id`),
  INDEX `reminder_to_task_idx` (`task_id_reference` ASC) VISIBLE,
  CONSTRAINT `reminder_to_task`
    FOREIGN KEY (`task_id_reference`)
    REFERENCES `todo_single_user`.`tasks` (`taks_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
