-- MySQL Script generated by MySQL Workbench
-- Wed Aug  1 02:13:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UNICEF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UNICEF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UNICEF` DEFAULT CHARACTER SET utf8 ;
USE `UNICEF` ;

-- -----------------------------------------------------
-- Table `UNICEF`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number_of_employees` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `targeted_groups` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dependencies` TINYINT(1) NOT NULL DEFAULT 0,
  `employment_date` DATE NULL,
  `employee_number` INT NOT NULL,
  `sections_sec_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sections_sec_id`, `project_id`),
  UNIQUE INDEX `employee_number_UNIQUE` (`employee_number` ASC),
  INDEX `fk_employee_sections1_idx` (`sections_sec_id` ASC),
  INDEX `fk_employee_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_employee_sections1`
    FOREIGN KEY (`sections_sec_id`)
    REFERENCES `UNICEF`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `UNICEF`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`NGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`NGO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `work_field` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`grant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `amount` INT NOT NULL,
  `donor_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`NGO_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`NGO_has_project` (
  `NGO_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`NGO_id`, `project_id`),
  INDEX `fk_NGO_has_project_project1_idx` (`project_id` ASC),
  INDEX `fk_NGO_has_project_NGO1_idx` (`NGO_id` ASC),
  CONSTRAINT `fk_NGO_has_project_NGO1`
    FOREIGN KEY (`NGO_id`)
    REFERENCES `UNICEF`.`NGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NGO_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `UNICEF`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`sections_has_grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`sections_has_grant` (
  `sections_sec_id` INT NOT NULL,
  `grant_id` INT NOT NULL,
  PRIMARY KEY (`sections_sec_id`, `grant_id`),
  INDEX `fk_sections_has_grant_grant1_idx` (`grant_id` ASC),
  INDEX `fk_sections_has_grant_sections1_idx` (`sections_sec_id` ASC),
  CONSTRAINT `fk_sections_has_grant_sections1`
    FOREIGN KEY (`sections_sec_id`)
    REFERENCES `UNICEF`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_has_grant_grant1`
    FOREIGN KEY (`grant_id`)
    REFERENCES `UNICEF`.`grant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNICEF`.`sections_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UNICEF`.`sections_has_project` (
  `sections_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`sections_id`, `project_id`),
  INDEX `fk_sections_has_project_project1_idx` (`project_id` ASC),
  INDEX `fk_sections_has_project_sections1_idx` (`sections_id` ASC),
  CONSTRAINT `fk_sections_has_project_sections1`
    FOREIGN KEY (`sections_id`)
    REFERENCES `UNICEF`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `UNICEF`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
